# Generated by Django 2.0.6 on 2019-03-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cwApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='superheromodel',
            name='city_or_origin',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='superheromodel',
            name='good_or_evil',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='superheromodel',
            name='name',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='superheromodel',
            name='powers',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='superheromodel',
            name='rich_or_superpowers',
            field=models.CharField(default='', max_length=500),
        ),
    ]
